Add wechat_pay source
omise/omise-dotnet pull request #81
Opened 2024-02-08 10:57 UTC by AnasNaouchi

## Description

Add `wechat_pay` source. More info could be found [here](https://docs.opn.ooo/wechat-pay-online)

*NOTE:*

* It is important to mention that when creating a `wechat_pay` source, it is advised to pass the `ip` parameter. This `ip` parameter should be the ip from the customer's device and not the server's ip.

2024-02-08 19:23 UTC, vault087 approved these changes

2024-02-09 02:37 UTC, danfowler approved these changes

2024-02-09 02:42 UTC, aashishgurung approved these changes

2024-02-12 04:08 UTC, danfowler commented on README.md
> +**Note:** It is important to mention that when creating a `wechat_pay` source it is advised to pass the `ip` param. This `ip` param should be the client's ip and not the server's ip.
```suggestion
**Note:** It is important to mention that when creating a `wechat_pay` source, it is advised to pass the `ip` parameter. This `ip` parameter should be the ip from the customer's device and not the server's ip.
```

2024-02-12 07:02 UTC, annatotest requested changes

2024-02-12 07:02 UTC, annatotest commented on Omise.Examples/Example.cs
> +        // Creates a new PaymentSource called RetrieveSourceRabbitLinepay, as sources can be created client-side (as well as server-side).
I think this called WeChat Pay rather than RabbitLinepay

2024-02-12 07:02 UTC, annatotest commented on Omise.Examples/Examples/PaymentSources.cs
> +            return RetrieveSourceRabbitLinepay().Result.Id;
The same here: not RabbitLinepay, but WeChat Pay

2024-02-12 07:17 UTC, aashishgurung approved these changes

2024-02-12 07:45 UTC, annatotest approved these changes

2024-02-12 09:57 UTC, danfowler approved these changes

2024-02-14 06:53 UTC, merged