Update readme
omise/omise-dotnet pull request #93
Opened 2024-09-08 20:30 UTC by AnasNaouchi

## Description

Update readme to include the info for the supported omise api and .NET versions.

2024-09-09 04:02 UTC, muthuswamyopn requested changes
**Omise.Net is a NuGet package for CLR platforms (.NET Standard) written in C#.**

Ambiguous as to what is written in C#. Is Omise.Net written in C#, or is it that Omise.Net can be used on all CLR platforms written in C#?

If it is the former, rewrite as:

**Omise.Net is a C# NuGet package for CLR platforms (.NET Standard).**

or better still:

**Omise.Net is a NuGet package for CLR platforms (.NET Standard) and is written in C#.**

If it is the latter, then rewrite as:

**Omise.Net is a NuGet package for CLR platforms (.NET Standard) that are written in C#**.

--------

**Although omise-dotnet can be used with other .NET versions, the versions listed below have been test-validated in our CI pipeline to ensure compatibility and stability.**

Rewrite as:

**Although you can use omise-dotnet with other .NET versions, we have validated the following versions in our CI pipeline to ensure compatibility and stability.**

Is the package called Omise.Net or is it omise-dotnet? Use one form.

2024-09-09 10:15 UTC, aashishgurung commented on README.md
> +| `omise-dotnet` Version | Supported Omise API Version | .NET Version(s) Supported                             | Type of Support         | Notes
- How about renaming `omise-dotnet Version` to `Library Version` or just `Version` and `Type of Support` to just `Support`?
- Moving `Support` next to `Version` would be more clear indicating that support refers to library support not API version support.

2024-09-10 04:39 UTC, muthuswamyopn approved these changes

2024-09-10 04:40 UTC, gaurab13 approved these changes

2024-09-10 08:09 UTC, aashishgurung approved these changes

2024-09-10 08:11 UTC, merged